
name: Python Code Check

on: [pull_request, push]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Code Check
        run: apt install flake8 && cd src/ && flake8 app.py