
name: Python Code Check

on: [pull_request, push]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Code Style
        uses: cclauss/Find-Python-syntax-errors-action@master