name: SonarCloud Scan (Pull Request)

on:
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=${{ secrets.SONARCLOUD_ORG_TOKEN }}
              -Dsonar.projectKey=DevOpsClassWork
              -Dsonar.python.coverage.reportPaths=coverage.xml